import type { CardTemplate } from './types'

export const CARD_TEMPLATES: Record<string, CardTemplate> = {
  char_reaper: {
    id: 'char_reaper',
    name: 'Reaper',
    type: 'character',
    description: '90 HP. Soul Slash (15 dmg, 2T CD) and Soul Slice (10 dmg per lane, 3T CD).',
    health: 90,
    vfx: 'reaper',
    abilities: [
      {
        id: 'soul_slash',
        name: 'Soul Slash',
        description: 'Deal 15 damage to one enemy.',
        effect: 'damage',
        damage: 15,
        cooldown: 2,
        targetType: 'enemy_character',
      },
      {
        id: 'soul_slice',
        name: 'Soul Slice',
        description: 'Deal 10 damage to every enemy in a horizontal row (lane).',
        effect: 'lane_damage',
        damage: 10,
        cooldown: 3,
        targetType: 'enemy_lane',
      },
    ],
  },
  char_banana: {
    id: 'char_banana',
    name: 'Banana Guy',
    type: 'character',
    description: '100 HP. Halve enemy damage forever (once) or self-destruct for 100 dmg.',
    health: 100,
    vfx: 'banana',
    abilities: [
      {
        id: 'banana_peel',
        name: 'Banana Peel',
        description: 'Chosen enemy deals half damage for the rest of the game. One use only.',
        effect: 'half_damage_debuff',
        cooldown: 0,
        oneTime: true,
        targetType: 'enemy_character',
      },
      {
        id: 'banana_boom',
        name: 'Banana Boom',
        description: 'Deal 100 damage but removes all Banana Guys from your deck.',
        effect: 'sacrifice_nuke',
        damage: 100,
        cooldown: 0,
        oneTime: true,
        targetType: 'enemy_character',
      },
    ],
  },
  char_spider: {
    id: 'char_spider',
    name: 'Spider',
    type: 'character',
    description: '110 HP. Web silences enemies. Infect deals DOT.',
    health: 110,
    vfx: 'spider',
    abilities: [
      {
        id: 'web',
        name: 'Web',
        description: 'Enemy cannot use attacks for 1 round. 2 turn cooldown.',
        effect: 'web',
        cooldown: 2,
        duration: 1,
        targetType: 'enemy_character',
      },
      {
        id: 'infect',
        name: 'Infect',
        description: 'Enemy takes 10 damage each round for 2 rounds. 3 turn cooldown.',
        effect: 'infect',
        cooldown: 3,
        duration: 2,
        dotDamage: 10,
        targetType: 'enemy_character',
      },
    ],
  },

  char_bottle: {
    id: 'char_bottle',
    name: 'Boutle',
    type: 'character',
    description: '120 HP. Boulder-turtle hybrid — quick bite or boulder roll lane attack.',
    health: 120,
    vfx: 'bottle',
    abilities: [
      {
        id: 'quick_bite',
        name: 'Quick Bite',
        description: 'Deal 10 damage to one enemy. 2 turn cooldown.',
        effect: 'damage',
        damage: 10,
        cooldown: 2,
        targetType: 'enemy_character',
        vfx: 'quick_bite',
      },
      {
        id: 'boulder_roll',
        name: 'Boulder Roll',
        description: 'Deal 10 damage to every enemy in a lane. 4 turn cooldown.',
        effect: 'lane_damage',
        damage: 10,
        cooldown: 4,
        targetType: 'enemy_lane',
        vfx: 'boulder_roll',
      },
    ],
  },

  char_healing_tree: {
    id: 'char_healing_tree',
    name: 'Healing Tree',
    type: 'character',
    description: '60 HP. Heals nearby allies or sacrifices to fully heal one ally.',
    health: 60,
    vfx: 'healing_tree',
    abilities: [
      {
        id: 'healing_essence',
        name: 'Healing Essence',
        description: 'Restore 20 HP to allied characters adjacent to this card. 3 turn cooldown.',
        effect: 'heal_adjacent',
        heal: 20,
        cooldown: 3,
        targetType: 'none',
        vfx: 'healing_essence',
      },
      {
        id: 'tree_sacrifice',
        name: 'Sacrifice',
        description: 'Destroy this card to fully heal one of your characters. One use only.',
        effect: 'sacrifice_heal_ally',
        cooldown: 0,
        oneTime: true,
        targetType: 'ally_character',
        vfx: 'sacrifice_heal',
      },
    ],
  },

  char_dud: {
    id: 'char_dud',
    name: 'Dud',
    type: 'character',
    description: '100 HP. Double hit or one-time attack immunity.',
    health: 100,
    vfx: 'dud',
    abilities: [
      {
        id: 'double_hit',
        name: 'Double Hit',
        description: 'Hit two different enemies for 10 damage each. 2 turn cooldown.',
        effect: 'double_target_damage',
        damage: 10,
        cooldown: 2,
        targetType: 'enemy_character',
        vfx: 'double_hit',
      },
      {
        id: 'immunity',
        name: 'Immunity',
        description: 'Immune to the next attack card used against this character. Uses your turn. One use only.',
        effect: 'self_immunity',
        cooldown: 4,
        oneTime: true,
        targetType: 'none',
        vfx: 'immunity',
      },
    ],
  },

  char_pigeon: {
    id: 'char_pigeon',
    name: 'Pigeon',
    type: 'character',
    description: '90 HP. Peck for damage + heal, or turd bomb plus-shaped AOE.',
    health: 90,
    vfx: 'pigeon',
    abilities: [
      {
        id: 'peck',
        name: 'Peck',
        description: 'Deal 10 damage to an enemy and heal yourself for 5 HP. 3 turn cooldown.',
        effect: 'damage_self_heal',
        damage: 10,
        heal: 5,
        cooldown: 3,
        targetType: 'enemy_character',
        vfx: 'peck',
      },
      {
        id: 'turd_bomb',
        name: 'Turd Bomb',
        description: 'Plus-shaped blast — up to 5 enemies take 20 damage each. 5 turn cooldown.',
        effect: 'aoe_plus_damage',
        damage: 20,
        cooldown: 5,
        targetType: 'enemy_aoe',
        vfx: 'turd_bomb',
      },
    ],
  },

  char_eye: {
    id: 'char_eye',
    name: 'The Eye',
    type: 'character',
    description: '100 HP. Stare to silence and haunt enemies.',
    health: 100,
    vfx: 'eye',
    abilities: [
      {
        id: 'stare',
        name: 'Stare',
        description: 'Deal 15 damage — enemy cannot act for 1 round. 3 turn cooldown.',
        effect: 'stare',
        damage: 15,
        cooldown: 3,
        duration: 1,
        targetType: 'enemy_character',
        vfx: 'stare',
      },
      {
        id: 'haunt',
        name: 'Haunt',
        description: 'Haunted enemy takes 10 damage whenever they attack (2 rounds). 4 turn cooldown.',
        effect: 'haunt_debuff',
        cooldown: 4,
        duration: 2,
        dotDamage: 10,
        targetType: 'enemy_character',
        vfx: 'haunt',
      },
    ],
  },

  char_redliner: {
    id: 'char_redliner',
    name: 'Redliner',
    type: 'character',
    description: '90 HP. Katana strikes build up to a devastating lane shot.',
    health: 90,
    vfx: 'redliner',
    abilities: [
      {
        id: 'katana_strike',
        name: 'Katana Strike',
        description: 'Deal 15 damage to one enemy. 1 turn cooldown.',
        effect: 'damage',
        damage: 15,
        cooldown: 1,
        targetType: 'enemy_character',
        vfx: 'katana_strike',
      },
      {
        id: 'redliner_shot',
        name: 'Shot',
        description: 'Lane attack for 30 damage each — requires 3 Katana Strikes first.',
        effect: 'conditional_lane_damage',
        damage: 30,
        cooldown: 6,
        targetType: 'enemy_lane',
        vfx: 'redliner_shot',
        requiresUses: { abilityId: 'katana_strike', count: 3 },
      },
    ],
  },

  atk_ice_surge: {
    id: 'atk_ice_surge',
    name: 'Ice Surge',
    type: 'attack',
    description: 'Freeze an enemy for 1 round and deal 15 damage.',
    effect: 'freeze_damage',
    damage: 15,
    duration: 1,
    vfx: 'freeze',
  },
  atk_pepper: {
    id: 'atk_pepper',
    name: 'Pepper',
    type: 'attack',
    description: 'Burn an enemy for 15 damage each round for 3 rounds.',
    effect: 'burn',
    duration: 3,
    dotDamage: 15,
    vfx: 'burn',
  },
  atk_tree: {
    id: 'atk_tree',
    name: 'Tree',
    type: 'attack',
    description: 'Obscure an enemy slot — they cannot place cards there for 2 rounds.',
    effect: 'obscure',
    duration: 2,
    vfx: 'tree',
  },
  atk_tornado: {
    id: 'atk_tornado',
    name: 'Tornado',
    type: 'attack',
    description: 'Pick an enemy character, then relocate them to any empty slot on their board.',
    effect: 'tornado_move',
    vfx: 'tornado',
  },
  atk_explosive: {
    id: 'atk_explosive',
    name: 'Explosive',
    type: 'attack',
    description: 'Choose a 2×2 area on the enemy board — 7 damage to each character hit.',
    effect: 'explosive_aoe',
    damage: 7,
    vfx: 'explosive',
  },
  atk_sweep: {
    id: 'atk_sweep',
    name: 'Sweep',
    type: 'attack',
    description: 'Unleash a wind column on the enemy board — 5 damage to each character in that column.',
    effect: 'column_sweep',
    damage: 5,
    vfx: 'sweep',
  },
  atk_spell_book: {
    id: 'atk_spell_book',
    name: 'Spell Book',
    type: 'attack',
    description: 'Reactive — when an enemy uses an attack or special card, cancel it and swap this card for the card they played.',
    effect: 'spell_book_reactive',
    vfx: 'spell_book',
  },
  atk_caffeinated: {
    id: 'atk_caffeinated',
    name: 'Caffeinated',
    type: 'attack',
    description: 'Your character ability cooldowns are reduced by 1 turn for 3 rounds.',
    effect: 'caffeinated_buff',
    duration: 3,
    vfx: 'caffeinated',
  },
  atk_chain_locked: {
    id: 'atk_chain_locked',
    name: 'Chain Locked',
    type: 'attack',
    description: 'Reactive — cancel an enemy attack or special and lock that card for both players for 3 turns.',
    effect: 'chain_locked_reactive',
    duration: 3,
    vfx: 'chain_locked',
  },

  spc_soul_revive: {
    id: 'spc_soul_revive',
    name: 'Soul Revive',
    type: 'special',
    description: 'Revive your last eliminated character into your hand.',
    effect: 'soul_revive',
    vfx: 'soul_revive',
  },
  spc_mirror: {
    id: 'spc_mirror',
    name: 'Mirror',
    type: 'special',
    description: 'When an enemy uses an attack card, counter within 5 seconds to reflect it back. Skips your next turn.',
    effect: 'mirror_reactive',
    vfx: 'mirror',
  },
  spc_quantity: {
    id: 'spc_quantity',
    name: 'Quantity',
    type: 'special',
    description: 'Hold 2 passive cards at once for 5 turns.',
    effect: 'quantity_buff',
    duration: 5,
    vfx: 'quantity',
  },
  spc_cannon: {
    id: 'spc_cannon',
    name: 'Cannon',
    type: 'special',
    description: 'Deal 75 damage to a chosen enemy.',
    effect: 'cannon_damage',
    damage: 75,
    vfx: 'cannon',
  },
  spc_cobweb: {
    id: 'spc_cobweb',
    name: 'Cobweb',
    type: 'special',
    description: 'Silence an enemy for 2 rounds — they cannot use abilities.',
    effect: 'cobweb',
    duration: 2,
    vfx: 'cobweb',
  },
  spc_ice_cream: {
    id: 'spc_ice_cream',
    name: 'Ice Cream',
    type: 'special',
    description: 'Freeze an entire enemy lane for 2 rounds — 10 damage each, cannot act.',
    effect: 'lane_freeze_damage',
    damage: 10,
    duration: 2,
    vfx: 'ice_cream',
  },
  spc_clock: {
    id: 'spc_clock',
    name: 'Clock',
    type: 'special',
    description: 'Pause all ability cooldowns on a chosen enemy for 2 rounds.',
    effect: 'cooldown_pause',
    duration: 2,
    vfx: 'clock',
  },
  spc_pickpocket: {
    id: 'spc_pickpocket',
    name: 'Pickpocket',
    type: 'special',
    description: 'Steal a random card from the enemy hand or deck.',
    effect: 'pickpocket_steal',
    vfx: 'pickpocket',
  },

  pas_shard: {
    id: 'pas_shard',
    name: 'Shard',
    type: 'passive',
    description: 'Your next attack deals 2× damage.',
    effect: 'shard_buff',
    buff: '2× Next Attack',
    vfx: 'shard',
  },
  pas_double_trouble: {
    id: 'pas_double_trouble',
    name: 'Double Trouble',
    type: 'passive',
    description: 'Next attack hits 2 different enemies (abilities & attack cards).',
    effect: 'double_trouble_buff',
    buff: 'Double Strike',
    vfx: 'double_trouble',
  },
  pas_trade: {
    id: 'pas_trade',
    name: 'Trade',
    type: 'passive',
    description: 'For 3 rounds: 1.5× dmg taken/dealt OR −1 cooldowns with 1.75× dmg taken.',
    effect: 'trade_buff',
    duration: 3,
    buff: 'Risk/Reward',
    vfx: 'trade',
  },
  pas_elemental_immunity: {
    id: 'pas_elemental_immunity',
    name: 'Elemental Immunity',
    type: 'passive',
    description: 'For 3 turns, your team is immune to Pepper, Ice Surge, Tornado, Tree, and Sweep.',
    effect: 'elemental_immunity_buff',
    duration: 3,
    buff: 'Elemental Ward',
    vfx: 'elemental_immunity',
  },
  pas_moonlight: {
    id: 'pas_moonlight',
    name: 'Moonlight',
    type: 'passive',
    description: 'Your next attack card (except Pepper) deals +5 damage.',
    effect: 'moonlight_buff',
    buff: '+5 Next Attack',
    vfx: 'moonlight',
  },
  pas_bread: {
    id: 'pas_bread',
    name: 'Bread',
    type: 'passive',
    description: 'For 3 turns, every elimination heals all your characters for 5 HP.',
    effect: 'bread_buff',
    duration: 3,
    buff: 'Comfort Food',
    vfx: 'bread',
  },
  pas_haunted: {
    id: 'pas_haunted',
    name: 'Haunted',
    type: 'passive',
    description: 'Your next attack inflicts Haunt (10 damage on attack, 2 rounds).',
    effect: 'haunted_buff',
    buff: 'Haunt Next Hit',
    vfx: 'haunted',
  },
  pas_chaos: {
    id: 'pas_chaos',
    name: 'Chaos',
    type: 'passive',
    description: 'Your next character ability becomes a 2×2 blast (not Soul Slice, Boulder Roll, Turd Bomb, or Shot).',
    effect: 'chaos_buff',
    buff: 'Chaotic Blast',
    vfx: 'chaos',
  },
  pas_musical_show: {
    id: 'pas_musical_show',
    name: 'Musical Show',
    type: 'passive',
    description: 'For 1 turn, take 2 consecutive turns when you act.',
    effect: 'musical_show_buff',
    duration: 1,
    buff: 'Encore',
    vfx: 'musical_show',
  },
  pas_thorn_mail: {
    id: 'pas_thorn_mail',
    name: 'Thorn Mail',
    type: 'passive',
    description: 'For 3 turns, enemies take 3 damage when they hit your characters.',
    effect: 'thorn_mail_buff',
    duration: 3,
    buff: 'Thorns',
    vfx: 'thorn_mail',
  },
  pas_regrowth: {
    id: 'pas_regrowth',
    name: 'Regrowth',
    type: 'passive',
    description: 'For 3 turns, heal your lowest-HP character for 5 at the start of each of your turns.',
    effect: 'regrowth_buff',
    duration: 3,
    buff: 'Renewal',
    vfx: 'regrowth',
  },
  pas_gamble: {
    id: 'pas_gamble',
    name: 'Gamble',
    type: 'passive',
    description: 'Flip a coin: heads = your next attack card deals 2× damage; tails = half damage.',
    effect: 'gamble_buff',
    buff: 'High Stakes',
    vfx: 'gamble',
  },
}

export const TEST_CARD_IDS = Object.keys(CARD_TEMPLATES)

export function getTemplate(templateId: string): CardTemplate {
  return CARD_TEMPLATES[templateId]
}

export function getAbility(templateId: string, abilityId: string) {
  return getTemplate(templateId).abilities?.find((a) => a.id === abilityId)
}
