/** Board-targeted VFX — rendered on the game board */
export const BOARD_VFX_TYPES = new Set([
  'soul_slice',
  'soul_slash',
  'banana_boom',
  'banana_peel',
  'web',
  'infect',
  'freeze',
  'burn',
  'tree',
  'tornado',
  'double_trouble',
  'character_deploy',
  'shard_strike',
  'damage',
  'quick_bite',
  'boulder_roll',
  'healing_essence',
  'sacrifice_heal',
  'double_hit',
  'immunity',
  'peck',
  'turd_bomb',
  'stare',
  'haunt',
  'haunt_recoil',
  'katana_strike',
  'redliner_shot',
  'explosive',
  'sweep',
  'chaos',
  'cannon_hit',
  'ice_cream_lane',
])

/** Full-screen / player-panel cinematic VFX */
export const SCREEN_VFX_TYPES = new Set([
  'shard',
  'shard_consume',
  'double_trouble_ready',
  'trade',
  'trade_damage',
  'trade_cooldown',
  'soul_revive',
  'quantity',
  'mirror',
  'mirror_reflect',
  'spell_book',
  'caffeinated',
  'chain_locked',
  'elemental_immunity',
  'moonlight',
  'bread',
  'haunted',
  'chaos',
  'musical_show',
  'thorn_mail',
  'regrowth',
  'gamble',
  'gamble_heads',
  'gamble_tails',
  'cannon',
  'cobweb',
  'ice_cream',
  'clock',
  'pickpocket',
])

export const VFX_DURATIONS: Record<string, number> = {
  soul_slice: 1600,
  soul_slash: 1500,
  banana_boom: 1800,
  banana_peel: 1600,
  web: 1800,
  infect: 1800,
  freeze: 1800,
  burn: 1800,
  tree: 2000,
  tornado: 1100,
  double_trouble: 1600,
  character_deploy: 1500,
  shard_strike: 1600,
  damage: 1200,
  quick_bite: 1400,
  boulder_roll: 1700,
  healing_essence: 1000,
  sacrifice_heal: 1100,
  double_hit: 1300,
  immunity: 1500,
  peck: 1500,
  turd_bomb: 2400,
  stare: 1700,
  haunt: 1600,
  haunt_recoil: 1200,
  katana_strike: 1400,
  redliner_shot: 1800,
  explosive: 2200,
  sweep: 1400,
  shard: 2400,
  shard_consume: 2000,
  double_trouble_ready: 2200,
  trade: 2400,
  trade_damage: 2400,
  trade_cooldown: 2400,
  soul_revive: 2800,
  quantity: 2200,
  mirror: 2400,
  mirror_reflect: 2200,
  spell_book: 2600,
  caffeinated: 2400,
  chain_locked: 2600,
  elemental_immunity: 2400,
  moonlight: 2200,
  bread: 2200,
  haunted: 2400,
  chaos: 2600,
  musical_show: 2600,
  thorn_mail: 2400,
  regrowth: 2200,
  gamble: 3800,
  gamble_heads: 3800,
  gamble_tails: 3800,
  cannon: 3200,
  cobweb: 3000,
  ice_cream: 1600,
  clock: 3000,
  pickpocket: 3200,
  cannon_hit: 2000,
  ice_cream_lane: 1300,
}

export function slotClass(row: number, col: number) {
  return `board-vfx--slot-${row}-${col}`
}

export function rowClass(row: number) {
  return `board-vfx--row-${row}`
}
